---
title: Bristol DUG
subtitle: The Bristol Drupal User Group.
email: info@drupalbristol.org.uk
default_date_format: 'jS F, Y'
fuzzy_date_format: F Y

imports:
    - venues.yml
    - events.yml

sponsors:
    - name: Sift
      website: http://www.sift.com/

    - name: Microserve
      website: https://microserve.io/

    - name: Halo
      website: http://wearehalo.co.uk/
